### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by prakharjoshi**
PR for master

### CODE REVIEW

**Comment by ebrehault** [comment]
@prakharjoshi I have wifi at the airport so I can review, I'll let you know.

**Comment by prakharjoshi** [comment]
Great !! 👍

**Comment by ebrehault** [comment]
@prakharjoshi merged !!! Thank you for your work, @obct537 and you did great.

**Comment by prakharjoshi** [comment]
@ebrehault seems like we have removed creation of document, instead we are now using service to create news ?

**Comment by ebrehault** [comment]
@prakharjoshi yes I have moved the createblogpost thing from /home to /blogpost, and I have fixed the service so we use the "News Item" content type instead of the "Document" content-type (and instead of using the /blog folder in the backend, we use now the /news folder).

**Pull request merged**
